root_0 = Category.create(name: "レディース")
child_0 = root_0.children.create(name: "トップス")
child_0.children.create(name: "Tシャツ/カットソー(半袖/袖なし)")
child_0.children.create(name: "Tシャツ/カットソー(七分/長袖)")
child_0.children.create(name: "シャツ/ブラウス(半袖/袖なし)")
child_0.children.create(name: "シャツ/ブラウス(七分/長袖)")
child_0.children.create(name: "ポロシャツ")
child_0.children.create(name: "キャミソール")
child_0.children.create(name: "タンクトップ")
child_0.children.create(name: "ホルターネック")
child_0.children.create(name: "ニット/セーター")
child_0.children.create(name: "チュニック")
child_0.children.create(name: "カーディガン/ボレロ")
child_0.children.create(name: "アンサンブル")
child_0.children.create(name: "ベスト/ジレ")
child_0.children.create(name: "パーカー")
child_1 = root_0.children.create(name: "ジャケット/アウター")
child_1.children.create(name: "テーラードジャケット")
child_1.children.create(name: "ノーカラージャケット")
child_1.children.create(name: "Gジャン/デニムジャケット")
child_1.children.create(name: "レザージャケット")
child_1.children.create(name: "ダウンジャケット")
child_1.children.create(name: "ライダースジャケット")
child_1.children.create(name: "ミリタリージャケット")
child_1.children.create(name: "ダウンベスト")
child_1.children.create(name: "ジャンパー/ブルゾン")
child_1.children.create(name: "ポンチョ")
child_1.children.create(name: "ロングコート")
child_1.children.create(name: "トレンチコート")
child_1.children.create(name: "ダッフルコート")
child_1.children.create(name: "ピーコート")
child_2 = root_0.children.create(name: "パンツ")
child_2.children.create(name: "デニム/ジーンズ")
child_2.children.create(name: "ショートパンツ")
child_2.children.create(name: "カジュアルパンツ")
child_2.children.create(name: "ハーフパンツ")
child_2.children.create(name: "チノパン")
child_2.children.create(name: "ワークパンツ/カーゴパンツ")
child_2.children.create(name: "クロップドパンツ")
child_2.children.create(name: "サロペット/オーバーオール")
child_2.children.create(name: "オールインワン")
child_2.children.create(name: "サルエルパンツ")
child_2.children.create(name: "ガウチョパンツ")
child_2.children.create(name: "その他")
child_3 = root_0.children.create(name: "スカート")
child_3.children.create(name: "ミニスカート")
child_3.children.create(name: "ひざ丈スカート")
child_3.children.create(name: "ロングスカート")
child_3.children.create(name: "キュロット")
child_3.children.create(name: "その他")
child_4 = root_0.children.create(name: "ワンピース")
child_4.children.create(name: "ミニワンピース")
child_4.children.create(name: "ひざ丈ワンピース")
child_4.children.create(name: "ロングワンピース")
child_4.children.create(name: "その他")
child_5 = root_0.children.create(name: "靴")
child_5.children.create(name: "ハイヒール/パンプス")
child_5.children.create(name: "ブーツ")
child_5.children.create(name: "サンダル")
child_5.children.create(name: "スニーカー")
child_5.children.create(name: "ミュール")
child_5.children.create(name: "モカシン")
child_5.children.create(name: "ローファー/革靴")
child_5.children.create(name: "フラットシューズ/バレエシューズ")
child_5.children.create(name: "長靴/レインシューズ")
child_5.children.create(name: "その他")
child_6 = root_0.children.create(name: "ルームウェア/パジャマ")
child_6.children.create(name: "パジャマ")
child_6.children.create(name: "ルームウェア")
child_7 = root_0.children.create(name: "レッグウェア")
child_7.children.create(name: "ソックス")
child_7.children.create(name: "スパッツ/レギンス")
child_7.children.create(name: "ストッキング/タイツ")
child_7.children.create(name: "レッグウォーマー")
child_7.children.create(name: "その他")
child_8 = root_0.children.create(name: "帽子")
child_8.children.create(name: "ニットキャップ/ビーニー")
child_8.children.create(name: "ハット")
child_8.children.create(name: "ハンチング/ベレー帽")
child_8.children.create(name: "キャップ")
child_8.children.create(name: "キャスケット")
child_8.children.create(name: "麦わら帽子")
child_8.children.create(name: "その他")
child_9 = root_0.children.create(name: "バッグ")
child_9.children.create(name: "ハンドバッグ")
child_9.children.create(name: "トートバッグ")
child_9.children.create(name: "エコバッグ")
child_9.children.create(name: "リュック/バックパック")
child_9.children.create(name: "ボストンバッグ")
child_9.children.create(name: "スポーツバッグ")
child_9.children.create(name: "ショルダーバッグ")
child_9.children.create(name: "クラッチバッグ")
child_9.children.create(name: "ポーチ/バニティ")
child_9.children.create(name: "ボディバッグ/ウェストバッグ")
child_9.children.create(name: "マザーズバッグ")
child_9.children.create(name: "メッセンジャーバッグ")
child_9.children.create(name: "ビジネスバッグ")
child_9.children.create(name: "旅行用バッグ/キャリーバッグ")
child_10 = root_0.children.create(name: "アクセサリー")
child_10.children.create(name: "ネックレス")
child_10.children.create(name: "ブレスレット")
child_10.children.create(name: "バングル/リストバンド")
child_10.children.create(name: "リング")
child_10.children.create(name: "ピアス(片耳用)")
child_10.children.create(name: "ピアス(両耳用)")
child_10.children.create(name: "イヤリング")
child_10.children.create(name: "アンクレット")
child_10.children.create(name: "ブローチ/コサージュ")
child_10.children.create(name: "チャーム")
child_10.children.create(name: "その他")
child_11 = root_0.children.create(name: "ヘアアクセサリー")
child_11.children.create(name: "ヘアゴム/シュシュ")
child_11.children.create(name: "ヘアバンド/カチューシャ")
child_11.children.create(name: "ヘアピン")
child_11.children.create(name: "その他")
child_12 = root_0.children.create(name: "小物")
child_12.children.create(name: "長財布")
child_12.children.create(name: "折り財布")
child_12.children.create(name: "コインケース/小銭入れ")
child_12.children.create(name: "名刺入れ/定期入れ")
child_12.children.create(name: "キーケース")
child_12.children.create(name: "キーホルダー")
child_12.children.create(name: "手袋/アームカバー")
child_12.children.create(name: "ハンカチ")
child_12.children.create(name: "ベルト")
child_12.children.create(name: "マフラー/ショール")
child_12.children.create(name: "ストール/スヌード")
child_12.children.create(name: "バンダナ/スカーフ")
child_12.children.create(name: "ネックウォーマー")
child_12.children.create(name: "サスペンダー")
child_13 = root_0.children.create(name: "時計")
child_13.children.create(name: "腕時計(アナログ)")
child_13.children.create(name: "腕時計(デジタル)")
child_13.children.create(name: "ラバーベルト")
child_13.children.create(name: "レザーベルト")
child_13.children.create(name: "金属ベルト")
child_13.children.create(name: "その他")
root_1 = Category.create(name: "メンズ")
child_0 = root_1.children.create(name: "トップス")
child_0.children.create(name: "Tシャツ/カットソー(半袖/袖なし)")
child_0.children.create(name: "Tシャツ/カットソー(七分/長袖)")
child_0.children.create(name: "シャツ")
child_0.children.create(name: "ポロシャツ")
child_0.children.create(name: "タンクトップ")
child_0.children.create(name: "ニット/セーター")
child_0.children.create(name: "パーカー")
child_0.children.create(name: "カーディガン")
child_0.children.create(name: "スウェット")
child_0.children.create(name: "ジャージ")
child_0.children.create(name: "ベスト")
child_0.children.create(name: "その他")
child_1 = root_1.children.create(name: "ジャケット/アウター")
child_1.children.create(name: "テーラードジャケット")
child_1.children.create(name: "ノーカラージャケット")
child_1.children.create(name: "Gジャン/デニムジャケット")
child_1.children.create(name: "レザージャケット")
child_1.children.create(name: "ダウンジャケット")
child_1.children.create(name: "ライダースジャケット")
child_1.children.create(name: "ミリタリージャケット")
child_1.children.create(name: "ナイロンジャケット")
child_1.children.create(name: "フライトジャケット")
child_1.children.create(name: "ダッフルコート")
child_1.children.create(name: "ピーコート")
child_1.children.create(name: "ステンカラーコート")
child_1.children.create(name: "トレンチコート")
child_1.children.create(name: "モッズコート")
child_2 = root_1.children.create(name: "パンツ")
child_2.children.create(name: "デニム/ジーンズ")
child_2.children.create(name: "ワークパンツ/カーゴパンツ")
child_2.children.create(name: "スラックス")
child_2.children.create(name: "チノパン")
child_2.children.create(name: "ショートパンツ")
child_2.children.create(name: "ペインターパンツ")
child_2.children.create(name: "サルエルパンツ")
child_2.children.create(name: "オーバーオール")
child_2.children.create(name: "その他")
child_3 = root_1.children.create(name: "靴")
child_3.children.create(name: "スニーカー")
child_3.children.create(name: "サンダル")
child_3.children.create(name: "ブーツ")
child_3.children.create(name: "モカシン")
child_3.children.create(name: "ドレス/ビジネス")
child_3.children.create(name: "長靴/レインシューズ")
child_3.children.create(name: "デッキシューズ")
child_3.children.create(name: "その他")
child_4 = root_1.children.create(name: "バッグ")
child_4.children.create(name: "ショルダーバッグ")
child_4.children.create(name: "トートバッグ")
child_4.children.create(name: "ボストンバッグ")
child_4.children.create(name: "リュック/バックパック")
child_4.children.create(name: "ウエストポーチ")
child_4.children.create(name: "ボディーバッグ")
child_4.children.create(name: "ドラムバッグ")
child_4.children.create(name: "ビジネスバッグ")
child_4.children.create(name: "トラベルバッグ")
child_4.children.create(name: "メッセンジャーバッグ")
child_4.children.create(name: "エコバッグ")
child_4.children.create(name: "その他")
child_5 = root_1.children.create(name: "スーツ")
child_5.children.create(name: "スーツジャケット")
child_5.children.create(name: "スーツベスト")
child_5.children.create(name: "スラックス")
child_5.children.create(name: "セットアップ")
child_5.children.create(name: "その他")
child_6 = root_1.children.create(name: "帽子")
child_6.children.create(name: "キャップ")
child_6.children.create(name: "ハット")
child_6.children.create(name: "ニットキャップ/ビーニー")
child_6.children.create(name: "ハンチング/ベレー帽")
child_6.children.create(name: "キャスケット")
child_6.children.create(name: "サンバイザー")
child_6.children.create(name: "その他")
child_7 = root_1.children.create(name: "アクセサリー")
child_7.children.create(name: "ネックレス")
child_7.children.create(name: "ブレスレット")
child_7.children.create(name: "バングル/リストバンド")
child_7.children.create(name: "リング")
child_7.children.create(name: "ピアス(片耳用)")
child_7.children.create(name: "ピアス(両耳用)")
child_7.children.create(name: "アンクレット")
child_7.children.create(name: "その他")
child_8 = root_1.children.create(name: "小物")
child_8.children.create(name: "長財布")
child_8.children.create(name: "折り財布")
child_8.children.create(name: "マネークリップ")
child_8.children.create(name: "コインケース/小銭入れ")
child_8.children.create(name: "名刺入れ/定期入れ")
child_8.children.create(name: "キーケース")
child_8.children.create(name: "キーホルダー")
child_8.children.create(name: "ネクタイ")
child_8.children.create(name: "手袋")
child_8.children.create(name: "ハンカチ")
child_8.children.create(name: "ベルト")
child_8.children.create(name: "マフラー")
child_8.children.create(name: "ストール")
child_8.children.create(name: "バンダナ")
child_9 = root_1.children.create(name: "時計")
child_9.children.create(name: "腕時計(アナログ)")
child_9.children.create(name: "腕時計(デジタル)")
child_9.children.create(name: "ラバーベルト")
child_9.children.create(name: "レザーベルト")
child_9.children.create(name: "金属ベルト")
child_9.children.create(name: "その他")
child_10 = root_1.children.create(name: "水着")
child_10.children.create(name: "一般水着")
child_10.children.create(name: "スポーツ用")
child_10.children.create(name: "アクセサリー")
child_10.children.create(name: "その他")
child_11 = root_1.children.create(name: "レッグウェア")
child_11.children.create(name: "ソックス")
child_11.children.create(name: "レギンス/スパッツ")
child_11.children.create(name: "レッグウォーマー")
child_11.children.create(name: "その他")
child_12 = root_1.children.create(name: "アンダーウェア")
child_12.children.create(name: "トランクス")
child_12.children.create(name: "ボクサーパンツ")
child_12.children.create(name: "その他")
root_2 = Category.create(name: "ベビー・キッズ")
child_0 = root_2.children.create(name: "ベビー服(女の子用)  ~95cm")
child_0.children.create(name: "トップス")
child_0.children.create(name: "アウター")
child_0.children.create(name: "パンツ")
child_0.children.create(name: "スカート")
child_0.children.create(name: "ワンピース")
child_0.children.create(name: "ベビードレス")
child_0.children.create(name: "おくるみ")
child_0.children.create(name: "下着/肌着")
child_0.children.create(name: "パジャマ")
child_0.children.create(name: "ロンパース")
child_0.children.create(name: "その他")
child_1 = root_2.children.create(name: "ベビー服(男の子用)  ~95cm")
child_1.children.create(name: "トップス")
child_1.children.create(name: "アウター")
child_1.children.create(name: "パンツ")
child_1.children.create(name: "おくるみ")
child_1.children.create(name: "下着/肌着")
child_1.children.create(name: "パジャマ")
child_1.children.create(name: "ロンパース")
child_1.children.create(name: "その他")
child_2 = root_2.children.create(name: "ベビー服(男女兼用)  ~95cm")
child_2.children.create(name: "トップス")
child_2.children.create(name: "アウター")
child_2.children.create(name: "パンツ")
child_2.children.create(name: "おくるみ")
child_2.children.create(name: "下着/肌着")
child_2.children.create(name: "パジャマ")
child_2.children.create(name: "ロンパース")
child_2.children.create(name: "その他")
child_3 = root_2.children.create(name: "キッズ服(女の子用) 100cm~")
child_3.children.create(name: "コート")
child_3.children.create(name: "ジャケット/上着")
child_3.children.create(name: "トップス(Tシャツ/カットソー)")
child_3.children.create(name: "トップス(トレーナー)")
child_3.children.create(name: "トップス(チュニック)")
child_3.children.create(name: "トップス(タンクトップ)")
child_3.children.create(name: "トップス(その他)")
child_3.children.create(name: "スカート")
child_3.children.create(name: "パンツ")
child_3.children.create(name: "ワンピース")
child_3.children.create(name: "セットアップ")
child_3.children.create(name: "パジャマ")
child_3.children.create(name: "フォーマル/ドレス")
child_3.children.create(name: "和服")
child_4 = root_2.children.create(name: "キッズ服(男の子用) 100cm~")
child_4.children.create(name: "コート")
child_4.children.create(name: "ジャケット/上着")
child_4.children.create(name: "トップス(Tシャツ/カットソー)")
child_4.children.create(name: "トップス(トレーナー)")
child_4.children.create(name: "トップス(その他)")
child_4.children.create(name: "パンツ")
child_4.children.create(name: "セットアップ")
child_4.children.create(name: "パジャマ")
child_4.children.create(name: "フォーマル/ドレス")
child_4.children.create(name: "和服")
child_4.children.create(name: "浴衣")
child_4.children.create(name: "甚平")
child_4.children.create(name: "水着")
child_4.children.create(name: "その他")
child_5 = root_2.children.create(name: "キッズ服(男女兼用) 100cm~")
child_5.children.create(name: "コート")
child_5.children.create(name: "ジャケット/上着")
child_5.children.create(name: "トップス(Tシャツ/カットソー)")
child_5.children.create(name: "トップス(トレーナー)")
child_5.children.create(name: "トップス(その他)")
child_5.children.create(name: "ボトムス")
child_5.children.create(name: "パジャマ")
child_5.children.create(name: "その他")
child_6 = root_2.children.create(name: "キッズ靴")
child_6.children.create(name: "スニーカー")
child_6.children.create(name: "サンダル")
child_6.children.create(name: "ブーツ")
child_6.children.create(name: "長靴")
child_6.children.create(name: "その他")
child_7 = root_2.children.create(name: "子ども用ファッション小物")
child_7.children.create(name: "靴下/スパッツ")
child_7.children.create(name: "帽子")
child_7.children.create(name: "エプロン")
child_7.children.create(name: "サスペンダー")
child_7.children.create(name: "タイツ")
child_7.children.create(name: "ハンカチ")
child_7.children.create(name: "バンダナ")
child_7.children.create(name: "ベルト")
child_7.children.create(name: "マフラー")
child_7.children.create(name: "傘")
child_7.children.create(name: "手袋")
child_7.children.create(name: "スタイ")
child_7.children.create(name: "バッグ")
child_7.children.create(name: "その他")
child_8 = root_2.children.create(name: "おむつ/トイレ/バス")
child_8.children.create(name: "おむつ用品")
child_8.children.create(name: "おまる/補助便座")
child_8.children.create(name: "トレーニングパンツ")
child_8.children.create(name: "ベビーバス")
child_8.children.create(name: "お風呂用品")
child_8.children.create(name: "その他")
child_9 = root_2.children.create(name: "外出/移動用品")
child_9.children.create(name: "ベビーカー")
child_9.children.create(name: "抱っこひも/スリング")
child_9.children.create(name: "チャイルドシート")
child_9.children.create(name: "その他")
child_10 = root_2.children.create(name: "授乳/食事")
child_10.children.create(name: "ミルク")
child_10.children.create(name: "ベビーフード")
child_10.children.create(name: "ベビー用食器")
child_10.children.create(name: "その他")
child_11 = root_2.children.create(name: "ベビー家具/寝具/室内用品")
child_11.children.create(name: "ベッド")
child_11.children.create(name: "布団/毛布")
child_11.children.create(name: "イス")
child_11.children.create(name: "たんす")
child_11.children.create(name: "その他")
child_12 = root_2.children.create(name: "おもちゃ")
child_12.children.create(name: "おふろのおもちゃ")
child_12.children.create(name: "がらがら")
child_12.children.create(name: "オルゴール")
child_12.children.create(name: "ベビージム")
child_12.children.create(name: "手押し車/カタカタ")
child_12.children.create(name: "知育玩具")
child_12.children.create(name: "その他")
child_13 = root_2.children.create(name: "行事/記念品")
child_13.children.create(name: "お宮参り用品")
child_13.children.create(name: "お食い初め用品")
child_13.children.create(name: "アルバム")
child_13.children.create(name: "手形/足形")
child_13.children.create(name: "その他")
root_3 = Category.create(name: "インテリア・住まい・小物")
child_0 = root_3.children.create(name: "キッチン/食器")
child_0.children.create(name: "食器")
child_0.children.create(name: "調理器具")
child_0.children.create(name: "収納/キッチン雑貨")
child_0.children.create(name: "弁当用品")
child_0.children.create(name: "カトラリー(スプーン等)")
child_0.children.create(name: "テーブル用品")
child_0.children.create(name: "容器")
child_0.children.create(name: "エプロン")
child_0.children.create(name: "アルコールグッズ")
child_0.children.create(name: "浄水機")
child_0.children.create(name: "その他")
child_1 = root_3.children.create(name: "ベッド/マットレス")
child_1.children.create(name: "セミシングルベッド")
child_1.children.create(name: "シングルベッド")
child_1.children.create(name: "セミダブルベッド")
child_1.children.create(name: "ダブルベッド")
child_1.children.create(name: "ワイドダブルベッド")
child_1.children.create(name: "クイーンベッド")
child_1.children.create(name: "キングベッド")
child_1.children.create(name: "脚付きマットレスベッド")
child_1.children.create(name: "マットレス")
child_1.children.create(name: "すのこベッド")
child_1.children.create(name: "ロフトベッド/システムベッド")
child_1.children.create(name: "簡易ベッド/折りたたみベッド")
child_1.children.create(name: "収納付き")
child_1.children.create(name: "その他")
child_2 = root_3.children.create(name: "ソファ/ソファベッド")
child_2.children.create(name: "ソファセット")
child_2.children.create(name: "シングルソファ")
child_2.children.create(name: "ラブソファ")
child_2.children.create(name: "トリプルソファ")
child_2.children.create(name: "オットマン")
child_2.children.create(name: "コーナーソファ")
child_2.children.create(name: "ビーズソファ/クッションソファ")
child_2.children.create(name: "ローソファ/フロアソファ")
child_2.children.create(name: "ソファベッド")
child_2.children.create(name: "応接セット")
child_2.children.create(name: "ソファカバー")
child_2.children.create(name: "リクライニングソファ")
child_2.children.create(name: "その他")
child_3 = root_3.children.create(name: "椅子/チェア")
child_3.children.create(name: "一般")
child_3.children.create(name: "スツール")
child_3.children.create(name: "ダイニングチェア")
child_3.children.create(name: "ハイバックチェア")
child_3.children.create(name: "ロッキングチェア")
child_3.children.create(name: "座椅子")
child_3.children.create(name: "折り畳みイス")
child_3.children.create(name: "デスクチェア")
child_3.children.create(name: "その他")
child_4 = root_3.children.create(name: "机/テーブル")
child_4.children.create(name: "こたつ")
child_4.children.create(name: "カウンターテーブル")
child_4.children.create(name: "サイドテーブル")
child_4.children.create(name: "センターテーブル")
child_4.children.create(name: "ダイニングテーブル")
child_4.children.create(name: "座卓/ちゃぶ台")
child_4.children.create(name: "アウトドア用")
child_4.children.create(name: "パソコン用")
child_4.children.create(name: "事務机/学習机")
child_4.children.create(name: "その他")
child_5 = root_3.children.create(name: "収納家具")
child_5.children.create(name: "リビング収納")
child_5.children.create(name: "キッチン収納")
child_5.children.create(name: "玄関/屋外収納")
child_5.children.create(name: "バス/トイレ収納")
child_5.children.create(name: "本収納")
child_5.children.create(name: "本/CD/DVD収納")
child_5.children.create(name: "洋服タンス/押入れ収納")
child_5.children.create(name: "電話台/ファックス台")
child_5.children.create(name: "ドレッサー/鏡台")
child_5.children.create(name: "棚/ラック")
child_5.children.create(name: "ケース/ボックス")
child_5.children.create(name: "その他")
child_6 = root_3.children.create(name: "ラグ/カーペット/マット")
child_6.children.create(name: "ラグ")
child_6.children.create(name: "カーペット")
child_6.children.create(name: "ホットカーペット")
child_6.children.create(name: "玄関/キッチンマット")
child_6.children.create(name: "トイレ/バスマット")
child_6.children.create(name: "その他")
child_7 = root_3.children.create(name: "カーテン/ブラインド")
child_7.children.create(name: "カーテン")
child_7.children.create(name: "ブラインド")
child_7.children.create(name: "ロールスクリーン")
child_7.children.create(name: "のれん")
child_7.children.create(name: "その他")
child_8 = root_3.children.create(name: "ライト/照明")
child_8.children.create(name: "蛍光灯/電球")
child_8.children.create(name: "天井照明")
child_8.children.create(name: "フロアスタンド")
child_8.children.create(name: "その他")
child_9 = root_3.children.create(name: "寝具")
child_9.children.create(name: "布団/毛布")
child_9.children.create(name: "枕")
child_9.children.create(name: "シーツ/カバー")
child_9.children.create(name: "その他")
child_10 = root_3.children.create(name: "インテリア小物")
child_10.children.create(name: "ごみ箱")
child_10.children.create(name: "ウェルカムボード")
child_10.children.create(name: "オルゴール")
child_10.children.create(name: "クッション")
child_10.children.create(name: "クッションカバー")
child_10.children.create(name: "スリッパラック")
child_10.children.create(name: "ティッシュボックス")
child_10.children.create(name: "バスケット/かご")
child_10.children.create(name: "フォトフレーム")
child_10.children.create(name: "マガジンラック")
child_10.children.create(name: "モビール")
child_10.children.create(name: "花瓶")
child_10.children.create(name: "灰皿")
child_10.children.create(name: "傘立て")
child_11 = root_3.children.create(name: "季節/年中行事")
child_11.children.create(name: "正月")
child_11.children.create(name: "成人式")
child_11.children.create(name: "バレンタインデー")
child_11.children.create(name: "ひな祭り")
child_11.children.create(name: "子どもの日")
child_11.children.create(name: "母の日")
child_11.children.create(name: "父の日")
child_11.children.create(name: "サマーギフト/お中元")
child_11.children.create(name: "夏/夏休み")
child_11.children.create(name: "ハロウィン")
child_11.children.create(name: "敬老の日")
child_11.children.create(name: "七五三")
child_11.children.create(name: "お歳暮")
child_11.children.create(name: "クリスマス")
root_4 = Category.create(name: "本・音楽・ゲーム")
child_0 = root_4.children.create(name: "本")
child_0.children.create(name: "文学/小説")
child_0.children.create(name: "人文/社会")
child_0.children.create(name: "ノンフィクション/教養")
child_0.children.create(name: "地図/旅行ガイド")
child_0.children.create(name: "ビジネス/経済")
child_0.children.create(name: "健康/医学")
child_0.children.create(name: "コンピュータ/IT")
child_0.children.create(name: "趣味/スポーツ/実用")
child_0.children.create(name: "住まい/暮らし/子育て")
child_0.children.create(name: "アート/エンタメ")
child_0.children.create(name: "洋書")
child_0.children.create(name: "絵本")
child_0.children.create(name: "参考書")
child_0.children.create(name: "その他")
child_1 = root_4.children.create(name: "漫画")
child_1.children.create(name: "全巻セット")
child_1.children.create(name: "少年漫画")
child_1.children.create(name: "少女漫画")
child_1.children.create(name: "青年漫画")
child_1.children.create(name: "女性漫画")
child_1.children.create(name: "同人誌")
child_1.children.create(name: "その他")
child_2 = root_4.children.create(name: "雑誌")
child_2.children.create(name: "アート/エンタメ/ホビー")
child_2.children.create(name: "ファッション")
child_2.children.create(name: "ニュース/総合")
child_2.children.create(name: "趣味/スポーツ")
child_2.children.create(name: "その他")
child_3 = root_4.children.create(name: "CD")
child_3.children.create(name: "邦楽")
child_3.children.create(name: "洋楽")
child_3.children.create(name: "アニメ")
child_3.children.create(name: "クラシック")
child_3.children.create(name: "K-POP/アジア")
child_3.children.create(name: "キッズ/ファミリー")
child_3.children.create(name: "その他")
child_4 = root_4.children.create(name: "DVD/ブルーレイ")
child_4.children.create(name: "外国映画")
child_4.children.create(name: "日本映画")
child_4.children.create(name: "アニメ")
child_4.children.create(name: "TVドラマ")
child_4.children.create(name: "ミュージック")
child_4.children.create(name: "お笑い/バラエティ")
child_4.children.create(name: "スポーツ/フィットネス")
child_4.children.create(name: "キッズ/ファミリー")
child_4.children.create(name: "その他")
child_5 = root_4.children.create(name: "レコード")
child_5.children.create(name: "邦楽")
child_5.children.create(name: "洋楽")
child_5.children.create(name: "その他")
child_6 = root_4.children.create(name: "テレビゲーム")
child_6.children.create(name: "家庭用ゲーム本体")
child_6.children.create(name: "家庭用ゲームソフト")
child_6.children.create(name: "携帯用ゲーム本体")
child_6.children.create(name: "携帯用ゲームソフト")
child_6.children.create(name: "PCゲーム")
child_6.children.create(name: "その他")
root_5 = Category.create(name: "おもちゃ・ホビー・グッズ")
child_0 = root_5.children.create(name: "おもちゃ")
child_0.children.create(name: "キャラクターグッズ")
child_0.children.create(name: "ぬいぐるみ")
child_0.children.create(name: "小物/アクセサリー")
child_0.children.create(name: "模型/プラモデル")
child_0.children.create(name: "ミニカー")
child_0.children.create(name: "トイラジコン")
child_0.children.create(name: "プラモデル")
child_0.children.create(name: "ホビーラジコン")
child_0.children.create(name: "鉄道模型")
child_0.children.create(name: "その他")
child_1 = root_5.children.create(name: "タレントグッズ")
child_1.children.create(name: "アイドル")
child_1.children.create(name: "ミュージシャン")
child_1.children.create(name: "タレント/お笑い芸人")
child_1.children.create(name: "スポーツ選手")
child_1.children.create(name: "その他")
child_2 = root_5.children.create(name: "コミック/アニメグッズ")
child_2.children.create(name: "ストラップ")
child_2.children.create(name: "キーホルダー")
child_2.children.create(name: "バッジ")
child_2.children.create(name: "カード")
child_2.children.create(name: "クリアファイル")
child_2.children.create(name: "ポスター")
child_2.children.create(name: "タオル")
child_2.children.create(name: "その他")
child_3 = root_5.children.create(name: "トレーディングカード")
child_3.children.create(name: "遊戯王")
child_3.children.create(name: "マジック：ザ・ギャザリング")
child_3.children.create(name: "ポケモンカードゲーム")
child_3.children.create(name: "デュエルマスターズ")
child_3.children.create(name: "バトルスピリッツ")
child_3.children.create(name: "プリパラ")
child_3.children.create(name: "アイカツ")
child_3.children.create(name: "カードファイト!! ヴァンガード")
child_3.children.create(name: "ヴァイスシュヴァルツ")
child_3.children.create(name: "プロ野球オーナーズリーグ")
child_3.children.create(name: "ベースボールヒーローズ")
child_3.children.create(name: "ドラゴンボール")
child_3.children.create(name: "スリーブ")
child_3.children.create(name: "その他")
child_4 = root_5.children.create(name: "フィギュア")
child_4.children.create(name: "コミック/アニメ")
child_4.children.create(name: "特撮")
child_4.children.create(name: "ゲームキャラクター")
child_4.children.create(name: "SF/ファンタジー/ホラー")
child_4.children.create(name: "アメコミ")
child_4.children.create(name: "スポーツ")
child_4.children.create(name: "ミリタリー")
child_4.children.create(name: "その他")
child_5 = root_5.children.create(name: "楽器/器材")
child_5.children.create(name: "エレキギター")
child_5.children.create(name: "アコースティックギター")
child_5.children.create(name: "ベース")
child_5.children.create(name: "エフェクター")
child_5.children.create(name: "アンプ")
child_5.children.create(name: "弦楽器")
child_5.children.create(name: "管楽器")
child_5.children.create(name: "鍵盤楽器")
child_5.children.create(name: "打楽器")
child_5.children.create(name: "和楽器")
child_5.children.create(name: "楽譜/スコア")
child_5.children.create(name: "レコーディング/PA機器")
child_5.children.create(name: "DJ機器")
child_5.children.create(name: "DTM/DAW")
child_6 = root_5.children.create(name: "コレクション")
child_6.children.create(name: "武具")
child_6.children.create(name: "使用済切手/官製はがき")
child_6.children.create(name: "旧貨幣/金貨/銀貨/記念硬貨")
child_6.children.create(name: "印刷物")
child_6.children.create(name: "ノベルティグッズ")
child_6.children.create(name: "その他")
child_7 = root_5.children.create(name: "ミリタリー")
child_7.children.create(name: "トイガン")
child_7.children.create(name: "個人装備")
child_7.children.create(name: "その他")
child_8 = root_5.children.create(name: "美術品")
child_8.children.create(name: "陶芸")
child_8.children.create(name: "ガラス")
child_8.children.create(name: "漆芸")
child_8.children.create(name: "金属工芸")
child_8.children.create(name: "絵画/タペストリ")
child_8.children.create(name: "版画")
child_8.children.create(name: "彫刻/オブジェクト")
child_8.children.create(name: "書")
child_8.children.create(name: "写真")
child_8.children.create(name: "その他")
child_9 = root_5.children.create(name: "アート用品")
child_9.children.create(name: "画材")
child_9.children.create(name: "額縁")
child_9.children.create(name: "その他")
child_10 = root_5.children.create(name: "その他")
child_10.children.create(name: "トランプ/UNO")
child_10.children.create(name: "カルタ/百人一首")
child_10.children.create(name: "ダーツ")
child_10.children.create(name: "ビリヤード")
child_10.children.create(name: "麻雀")
child_10.children.create(name: "パズル/ジグソーパズル")
child_10.children.create(name: "囲碁/将棋")
child_10.children.create(name: "オセロ/チェス")
child_10.children.create(name: "人生ゲーム")
child_10.children.create(name: "野球/サッカーゲーム")
child_10.children.create(name: "スポーツ")
child_10.children.create(name: "三輪車/乗り物")
child_10.children.create(name: "ヨーヨー")
child_10.children.create(name: "模型製作用品")
root_6 = Category.create(name: "コスメ・香水・美容")
child_0 = root_6.children.create(name: "ベースメイク")
child_0.children.create(name: "ファンデーション")
child_0.children.create(name: "化粧下地")
child_0.children.create(name: "コントロールカラー")
child_0.children.create(name: "BBクリーム")
child_0.children.create(name: "CCクリーム")
child_0.children.create(name: "コンシーラー")
child_0.children.create(name: "フェイスパウダー")
child_0.children.create(name: "トライアルセット/サンプル")
child_0.children.create(name: "その他")
child_1 = root_6.children.create(name: "メイクアップ")
child_1.children.create(name: "アイシャドウ")
child_1.children.create(name: "口紅")
child_1.children.create(name: "リップグロス")
child_1.children.create(name: "リップライナー")
child_1.children.create(name: "チーク")
child_1.children.create(name: "フェイスカラー")
child_1.children.create(name: "マスカラ")
child_1.children.create(name: "アイライナー")
child_1.children.create(name: "つけまつげ")
child_1.children.create(name: "アイブロウペンシル")
child_1.children.create(name: "パウダーアイブロウ")
child_1.children.create(name: "眉マスカラ")
child_1.children.create(name: "トライアルセット/サンプル")
child_1.children.create(name: "メイク道具/化粧小物")
child_2 = root_6.children.create(name: "ネイルケア")
child_2.children.create(name: "ネイルカラー")
child_2.children.create(name: "カラージェル")
child_2.children.create(name: "ネイルベースコート/トップコート")
child_2.children.create(name: "ネイルアート用品")
child_2.children.create(name: "ネイルパーツ")
child_2.children.create(name: "ネイルチップ/付け爪")
child_2.children.create(name: "手入れ用具")
child_2.children.create(name: "除光液")
child_2.children.create(name: "その他")
child_3 = root_6.children.create(name: "香水")
child_3.children.create(name: "香水(女性用)")
child_3.children.create(name: "香水(男性用)")
child_3.children.create(name: "ユニセックス")
child_3.children.create(name: "ボディミスト")
child_3.children.create(name: "その他")
child_4 = root_6.children.create(name: "スキンケア/基礎化粧品")
child_4.children.create(name: "化粧水/ローション")
child_4.children.create(name: "乳液/ミルク")
child_4.children.create(name: "美容液")
child_4.children.create(name: "フェイスクリーム")
child_4.children.create(name: "洗顔料")
child_4.children.create(name: "クレンジング/メイク落とし")
child_4.children.create(name: "パック/フェイスマスク")
child_4.children.create(name: "ジェル/ゲル")
child_4.children.create(name: "ブースター/導入液")
child_4.children.create(name: "アイケア")
child_4.children.create(name: "リップケア")
child_4.children.create(name: "トライアルセット/サンプル")
child_4.children.create(name: "洗顔グッズ")
child_4.children.create(name: "その他")
child_5 = root_6.children.create(name: "ヘアケア")
child_5.children.create(name: "シャンプー")
child_5.children.create(name: "トリートメント")
child_5.children.create(name: "コンディショナー")
child_5.children.create(name: "リンス")
child_5.children.create(name: "スタイリング剤")
child_5.children.create(name: "カラーリング剤")
child_5.children.create(name: "ブラシ")
child_5.children.create(name: "その他")
child_6 = root_6.children.create(name: "ボディケア")
child_6.children.create(name: "オイル/クリーム")
child_6.children.create(name: "ハンドクリーム")
child_6.children.create(name: "ローション")
child_6.children.create(name: "日焼け止め/サンオイル")
child_6.children.create(name: "ボディソープ")
child_6.children.create(name: "入浴剤")
child_6.children.create(name: "制汗/デオドラント")
child_6.children.create(name: "フットケア")
child_6.children.create(name: "その他")
child_7 = root_6.children.create(name: "オーラルケア")
child_7.children.create(name: "口臭防止/エチケット用品")
child_7.children.create(name: "歯ブラシ")
child_7.children.create(name: "その他")
child_8 = root_6.children.create(name: "リラクゼーション")
child_8.children.create(name: "エッセンシャルオイル")
child_8.children.create(name: "芳香器")
child_8.children.create(name: "お香/香炉")
child_8.children.create(name: "キャンドル")
child_8.children.create(name: "リラクゼーショングッズ")
child_8.children.create(name: "その他")
child_9 = root_6.children.create(name: "ダイエット")
child_9.children.create(name: "ダイエット食品")
child_9.children.create(name: "エクササイズ用品")
child_9.children.create(name: "体重計")
child_9.children.create(name: "体脂肪計")
child_9.children.create(name: "その他")
child_10 = root_6.children.create(name: "その他")
child_10.children.create(name: "健康用品")
child_10.children.create(name: "看護/介護用品")
child_10.children.create(name: "救急/衛生用品")
child_10.children.create(name: "その他")
root_7 = Category.create(name: "家電・スマホ・カメラ")
child_0 = root_7.children.create(name: "スマートフォン/携帯電話")
child_0.children.create(name: "スマートフォン本体")
child_0.children.create(name: "バッテリー/充電器")
child_0.children.create(name: "携帯電話本体")
child_0.children.create(name: "PHS本体")
child_0.children.create(name: "その他")
child_1 = root_7.children.create(name: "スマホアクセサリー")
child_1.children.create(name: "Android用ケース")
child_1.children.create(name: "iPhone用ケース")
child_1.children.create(name: "カバー")
child_1.children.create(name: "イヤホンジャック")
child_1.children.create(name: "ストラップ")
child_1.children.create(name: "フィルム")
child_1.children.create(name: "自撮り棒")
child_1.children.create(name: "その他")
child_2 = root_7.children.create(name: "PC/タブレット")
child_2.children.create(name: "タブレット")
child_2.children.create(name: "ノートPC")
child_2.children.create(name: "デスクトップ型PC")
child_2.children.create(name: "ディスプレイ")
child_2.children.create(name: "電子ブックリーダー")
child_2.children.create(name: "PC周辺機器")
child_2.children.create(name: "PCパーツ")
child_2.children.create(name: "その他")
child_3 = root_7.children.create(name: "カメラ")
child_3.children.create(name: "デジタルカメラ")
child_3.children.create(name: "ビデオカメラ")
child_3.children.create(name: "レンズ(単焦点)")
child_3.children.create(name: "レンズ(ズーム)")
child_3.children.create(name: "フィルムカメラ")
child_3.children.create(name: "防犯カメラ")
child_3.children.create(name: "その他")
child_4 = root_7.children.create(name: "テレビ/映像機器")
child_4.children.create(name: "テレビ")
child_4.children.create(name: "プロジェクター")
child_4.children.create(name: "ブルーレイレコーダー")
child_4.children.create(name: "DVDレコーダー")
child_4.children.create(name: "ブルーレイプレーヤー")
child_4.children.create(name: "DVDプレーヤー")
child_4.children.create(name: "映像用ケーブル")
child_4.children.create(name: "その他")
child_5 = root_7.children.create(name: "オーディオ機器")
child_5.children.create(name: "ポータブルプレーヤー")
child_5.children.create(name: "イヤフォン")
child_5.children.create(name: "ヘッドフォン")
child_5.children.create(name: "アンプ")
child_5.children.create(name: "スピーカー")
child_5.children.create(name: "ケーブル/シールド")
child_5.children.create(name: "ラジオ")
child_5.children.create(name: "その他")
child_6 = root_7.children.create(name: "美容/健康")
child_6.children.create(name: "ヘアドライヤー")
child_6.children.create(name: "ヘアアイロン")
child_6.children.create(name: "美容機器")
child_6.children.create(name: "電気シェーバー")
child_6.children.create(name: "電動歯ブラシ")
child_6.children.create(name: "その他")
child_7 = root_7.children.create(name: "冷暖房/空調")
child_7.children.create(name: "エアコン")
child_7.children.create(name: "空気清浄器")
child_7.children.create(name: "加湿器")
child_7.children.create(name: "扇風機")
child_7.children.create(name: "除湿機")
child_7.children.create(name: "ファンヒーター ")
child_7.children.create(name: "電気ヒーター")
child_7.children.create(name: "オイルヒーター")
child_7.children.create(name: "ストーブ")
child_7.children.create(name: "ホットカーペット")
child_7.children.create(name: "こたつ")
child_7.children.create(name: "電気毛布")
child_7.children.create(name: "その他")
child_8 = root_7.children.create(name: "生活家電")
child_8.children.create(name: "冷蔵庫")
child_8.children.create(name: "洗濯機")
child_8.children.create(name: "炊飯器")
child_8.children.create(name: "電子レンジ/オーブン")
child_8.children.create(name: "調理機器")
child_8.children.create(name: "アイロン")
child_8.children.create(name: "掃除機")
child_8.children.create(name: "エスプレッソマシン")
child_8.children.create(name: "コーヒーメーカー")
child_8.children.create(name: "衣類乾燥機")
child_8.children.create(name: "その他")
child_9 = root_7.children.create(name: "その他")
child_9.children.create(name: "その他")
root_8 = Category.create(name: "スポーツ・レジャー")
child_0 = root_8.children.create(name: "ゴルフ")
child_0.children.create(name: "クラブ")
child_0.children.create(name: "ウエア(男性用)")
child_0.children.create(name: "ウエア(女性用)")
child_0.children.create(name: "バッグ ")
child_0.children.create(name: "シューズ(男性用)")
child_0.children.create(name: "シューズ(女性用)")
child_0.children.create(name: "アクセサリー")
child_0.children.create(name: "その他")
child_1 = root_8.children.create(name: "フィッシング")
child_1.children.create(name: "ロッド")
child_1.children.create(name: "リール")
child_1.children.create(name: "ルアー用品")
child_1.children.create(name: "ウエア")
child_1.children.create(name: "釣り糸/ライン")
child_1.children.create(name: "その他")
child_2 = root_8.children.create(name: "自転車")
child_2.children.create(name: "自転車本体")
child_2.children.create(name: "ウエア")
child_2.children.create(name: "パーツ")
child_2.children.create(name: "アクセサリー")
child_2.children.create(name: "バッグ")
child_2.children.create(name: "工具/メンテナンス")
child_2.children.create(name: "その他")
child_3 = root_8.children.create(name: "トレーニング/エクササイズ")
child_3.children.create(name: "ランニング")
child_3.children.create(name: "ウォーキング")
child_3.children.create(name: "ヨガ")
child_3.children.create(name: "トレーニング用品")
child_3.children.create(name: "その他")
child_4 = root_8.children.create(name: "野球")
child_4.children.create(name: "ウェア")
child_4.children.create(name: "シューズ")
child_4.children.create(name: "グローブ")
child_4.children.create(name: "バット")
child_4.children.create(name: "アクセサリー")
child_4.children.create(name: "防具")
child_4.children.create(name: "練習機器")
child_4.children.create(name: "記念グッズ")
child_4.children.create(name: "応援グッズ")
child_4.children.create(name: "その他")
child_5 = root_8.children.create(name: "サッカー/フットサル")
child_5.children.create(name: "ウェア")
child_5.children.create(name: "シューズ")
child_5.children.create(name: "ボール")
child_5.children.create(name: "アクセサリー")
child_5.children.create(name: "記念グッズ")
child_5.children.create(name: "応援グッズ")
child_5.children.create(name: "その他")
child_6 = root_8.children.create(name: "テニス")
child_6.children.create(name: "ラケット(硬式用)")
child_6.children.create(name: "ラケット(軟式用)")
child_6.children.create(name: "ウェア")
child_6.children.create(name: "シューズ")
child_6.children.create(name: "ボール")
child_6.children.create(name: "アクセサリー")
child_6.children.create(name: "記念グッズ")
child_6.children.create(name: "応援グッズ")
child_6.children.create(name: "その他")
child_7 = root_8.children.create(name: "スノーボード")
child_7.children.create(name: "ボード")
child_7.children.create(name: "バインディング")
child_7.children.create(name: "ブーツ(男性用)")
child_7.children.create(name: "ブーツ(女性用)")
child_7.children.create(name: "ブーツ(子ども用)")
child_7.children.create(name: "ウエア/装備(男性用)")
child_7.children.create(name: "ウエア/装備(女性用)")
child_7.children.create(name: "ウエア/装備(子ども用)")
child_7.children.create(name: "アクセサリー")
child_7.children.create(name: "バッグ")
child_7.children.create(name: "その他")
child_8 = root_8.children.create(name: "スキー")
child_8.children.create(name: "板")
child_8.children.create(name: "ブーツ(男性用)")
child_8.children.create(name: "ブーツ(女性用)")
child_8.children.create(name: "ブーツ(子ども用)")
child_8.children.create(name: "ビンディング")
child_8.children.create(name: "ウエア(男性用)")
child_8.children.create(name: "ウエア(女性用)")
child_8.children.create(name: "ウエア(子ども用)")
child_8.children.create(name: "ストック")
child_8.children.create(name: "その他")
child_9 = root_8.children.create(name: "その他スポーツ")
child_9.children.create(name: "ダンス/バレエ")
child_9.children.create(name: "サーフィン")
child_9.children.create(name: "バスケットボール")
child_9.children.create(name: "バドミントン")
child_9.children.create(name: "バレーボール")
child_9.children.create(name: "スケートボード")
child_9.children.create(name: "陸上競技")
child_9.children.create(name: "ラグビー")
child_9.children.create(name: "アメリカンフットボール")
child_9.children.create(name: "ボクシング")
child_9.children.create(name: "ボウリング")
child_9.children.create(name: "その他")
child_10 = root_8.children.create(name: "アウトドア")
child_10.children.create(name: "テント/タープ")
child_10.children.create(name: "ライト/ランタン")
child_10.children.create(name: "寝袋/寝具")
child_10.children.create(name: "テーブル/チェア")
child_10.children.create(name: "ストーブ/コンロ")
child_10.children.create(name: "調理器具")
child_10.children.create(name: "食器")
child_10.children.create(name: "登山用品")
child_10.children.create(name: "その他")
child_11 = root_8.children.create(name: "その他")
child_11.children.create(name: "旅行用品")
child_11.children.create(name: "その他")
root_9 = Category.create(name: "ハンドメイド")
child_0 = root_9.children.create(name: "アクセサリー(女性用)")
child_0.children.create(name: "ピアス")
child_0.children.create(name: "イヤリング")
child_0.children.create(name: "ネックレス")
child_0.children.create(name: "ブレスレット")
child_0.children.create(name: "リング")
child_0.children.create(name: "チャーム")
child_0.children.create(name: "ヘアゴム")
child_0.children.create(name: "アンクレット")
child_0.children.create(name: "その他")
child_1 = root_9.children.create(name: "ファッション/小物")
child_1.children.create(name: "バッグ(女性用)")
child_1.children.create(name: "バッグ(男性用)")
child_1.children.create(name: "財布(女性用)")
child_1.children.create(name: "財布(男性用)")
child_1.children.create(name: "ファッション雑貨")
child_1.children.create(name: "その他")
child_2 = root_9.children.create(name: "アクセサリー/時計")
child_2.children.create(name: "アクセサリー(男性用)")
child_2.children.create(name: "時計(女性用)")
child_2.children.create(name: "時計(男性用)")
child_2.children.create(name: "その他")
child_3 = root_9.children.create(name: "日用品/インテリア")
child_3.children.create(name: "キッチン用品")
child_3.children.create(name: "家具")
child_3.children.create(name: "文房具")
child_3.children.create(name: "アート/写真")
child_3.children.create(name: "アロマ/キャンドル")
child_3.children.create(name: "フラワー/ガーデン")
child_3.children.create(name: "その他")
child_4 = root_9.children.create(name: "趣味/おもちゃ")
child_4.children.create(name: "クラフト/布製品")
child_4.children.create(name: "おもちゃ/人形")
child_4.children.create(name: "その他")
child_5 = root_9.children.create(name: "キッズ/ベビー")
child_5.children.create(name: "ファッション雑貨")
child_5.children.create(name: "スタイ/よだれかけ")
child_5.children.create(name: "外出用品")
child_5.children.create(name: "ネームタグ")
child_5.children.create(name: "その他")
child_6 = root_9.children.create(name: "素材/材料")
child_6.children.create(name: "各種パーツ")
child_6.children.create(name: "生地/糸")
child_6.children.create(name: "型紙/パターン")
child_6.children.create(name: "その他")
child_7 = root_9.children.create(name: "二次創作物")
child_7.children.create(name: "Ingress")
child_7.children.create(name: "クリエイターズ宇宙兄弟")
child_7.children.create(name: "シンデレラガールズCPグッズ")
root_10 = Category.create(name: "チケット")
child_0 = root_10.children.create(name: "音楽  ")
child_0.children.create(name: "男性アイドル")
child_0.children.create(name: "女性アイドル")
child_0.children.create(name: "韓流")
child_0.children.create(name: "国内アーティスト")
child_0.children.create(name: "海外アーティスト")
child_0.children.create(name: "音楽フェス")
child_0.children.create(name: "声優/アニメ")
child_0.children.create(name: "その他")
child_1 = root_10.children.create(name: "スポーツ")
child_1.children.create(name: "サッカー")
child_1.children.create(name: "野球")
child_1.children.create(name: "テニス")
child_1.children.create(name: "格闘技/プロレス")
child_1.children.create(name: "相撲/武道")
child_1.children.create(name: "ゴルフ")
child_1.children.create(name: "バレーボール")
child_1.children.create(name: "バスケットボール")
child_1.children.create(name: "モータースポーツ")
child_1.children.create(name: "ウィンタースポーツ")
child_1.children.create(name: "その他")
child_2 = root_10.children.create(name: "演劇/芸能")
child_2.children.create(name: "ミュージカル")
child_2.children.create(name: "演劇")
child_2.children.create(name: "伝統芸能")
child_2.children.create(name: "落語")
child_2.children.create(name: "お笑い")
child_2.children.create(name: "オペラ")
child_2.children.create(name: "サーカス")
child_2.children.create(name: "バレエ")
child_2.children.create(name: "その他")
child_3 = root_10.children.create(name: "イベント")
child_3.children.create(name: "声優/アニメ")
child_3.children.create(name: "キッズ/ファミリー")
child_3.children.create(name: "トークショー/講演会")
child_3.children.create(name: "その他")
child_4 = root_10.children.create(name: "映画")
child_4.children.create(name: "邦画")
child_4.children.create(name: "洋画")
child_4.children.create(name: "その他")
child_5 = root_10.children.create(name: "施設利用券")
child_5.children.create(name: "遊園地/テーマパーク")
child_5.children.create(name: "美術館/博物館")
child_5.children.create(name: "スキー場")
child_5.children.create(name: "ゴルフ場")
child_5.children.create(name: "フィットネスクラブ")
child_5.children.create(name: "プール")
child_5.children.create(name: "ボウリング場")
child_5.children.create(name: "水族館")
child_5.children.create(name: "動物園")
child_5.children.create(name: "その他")
child_6 = root_10.children.create(name: "優待券/割引券")
child_6.children.create(name: "ショッピング")
child_6.children.create(name: "レストラン/食事券")
child_6.children.create(name: "フード/ドリンク券")
child_6.children.create(name: "宿泊券")
child_6.children.create(name: "その他")
root_11 = Category.create(name: "自動車・オートバイ")
child_0 = root_11.children.create(name: "自動車本体")
child_0.children.create(name: "国内自動車本体")
child_0.children.create(name: "外国自動車本体")
child_1 = root_11.children.create(name: "自動車タイヤ/ホイール")
child_1.children.create(name: "タイヤ/ホイールセット")
child_1.children.create(name: "タイヤ")
child_1.children.create(name: "ホイール")
child_1.children.create(name: "その他")
child_2 = root_11.children.create(name: "自動車パーツ")
child_2.children.create(name: "サスペンション")
child_2.children.create(name: "ブレーキ")
child_2.children.create(name: "外装、エアロパーツ")
child_2.children.create(name: "ライト")
child_2.children.create(name: "内装品、シート")
child_2.children.create(name: "ステアリング")
child_2.children.create(name: "マフラー・排気系")
child_2.children.create(name: "エンジン、過給器、冷却装置")
child_2.children.create(name: "クラッチ、ミッション、駆動系")
child_2.children.create(name: "電装品")
child_2.children.create(name: "補強パーツ")
child_2.children.create(name: "汎用パーツ")
child_2.children.create(name: "外国自動車用パーツ")
child_2.children.create(name: "その他")
child_3 = root_11.children.create(name: "自動車アクセサリー")
child_3.children.create(name: "車内アクセサリー")
child_3.children.create(name: "カーナビ")
child_3.children.create(name: "カーオーディオ")
child_3.children.create(name: "車外アクセサリー")
child_3.children.create(name: "メンテナンス用品")
child_3.children.create(name: "チャイルドシート")
child_3.children.create(name: "ドライブレコーダー")
child_3.children.create(name: "レーダー探知機")
child_3.children.create(name: "カタログ/マニュアル")
child_3.children.create(name: "セキュリティ")
child_3.children.create(name: "ETC")
child_3.children.create(name: "その他")
child_4 = root_11.children.create(name: "オートバイパーツ")
child_4.children.create(name: "タイヤ")
child_4.children.create(name: "マフラー")
child_4.children.create(name: "エンジン、冷却装置")
child_4.children.create(name: "カウル、フェンダー、外装")
child_4.children.create(name: "サスペンション")
child_4.children.create(name: "ホイール")
child_4.children.create(name: "シート")
child_4.children.create(name: "ブレーキ")
child_4.children.create(name: "タンク")
child_4.children.create(name: "ライト、ウィンカー")
child_4.children.create(name: "チェーン、スプロケット、駆動系")
child_4.children.create(name: "メーター")
child_4.children.create(name: "電装系")
child_4.children.create(name: "ミラー")
child_5 = root_11.children.create(name: "オートバイアクセサリー")
child_5.children.create(name: "ヘルメット/シールド")
child_5.children.create(name: "バイクウエア/装備")
child_5.children.create(name: "アクセサリー")
child_5.children.create(name: "メンテナンス")
child_5.children.create(name: "カタログ/マニュアル")
child_5.children.create(name: "その他")
root_12 = Category.create(name: "その他")
child_0 = root_12.children.create(name: "ペット用品")
child_0.children.create(name: "ペットフード")
child_0.children.create(name: "犬用品")
child_0.children.create(name: "猫用品")
child_0.children.create(name: "魚用品/水草")
child_0.children.create(name: "小動物用品")
child_0.children.create(name: "爬虫類/両生類用品")
child_0.children.create(name: "かご/おり")
child_0.children.create(name: "鳥用品")
child_0.children.create(name: "虫類用品")
child_0.children.create(name: "その他")
child_1 = root_12.children.create(name: "食品")
child_1.children.create(name: "菓子")
child_1.children.create(name: "米")
child_1.children.create(name: "野菜")
child_1.children.create(name: "果物")
child_1.children.create(name: "調味料")
child_1.children.create(name: "魚介類(加工食品)")
child_1.children.create(name: "肉類(加工食品)")
child_1.children.create(name: "その他 加工食品")
child_1.children.create(name: "その他")
child_2 = root_12.children.create(name: "飲料/酒")
child_2.children.create(name: "コーヒー")
child_2.children.create(name: "ソフトドリンク")
child_2.children.create(name: "ミネラルウォーター")
child_2.children.create(name: "茶")
child_2.children.create(name: "ウイスキー")
child_2.children.create(name: "ワイン")
child_2.children.create(name: "ブランデー")
child_2.children.create(name: "焼酎")
child_2.children.create(name: "日本酒")
child_2.children.create(name: "ビール、発泡酒")
child_2.children.create(name: "その他")
child_3 = root_12.children.create(name: "日用品/生活雑貨/旅行")
child_3.children.create(name: "タオル/バス用品")
child_3.children.create(name: "日用品/生活雑貨")
child_3.children.create(name: "洗剤/柔軟剤")
child_3.children.create(name: "旅行用品")
child_3.children.create(name: "防災関連グッズ")
child_3.children.create(name: "その他")
child_4 = root_12.children.create(name: "アンティーク/コレクション")
child_4.children.create(name: "雑貨")
child_4.children.create(name: "工芸品")
child_4.children.create(name: "家具")
child_4.children.create(name: "印刷物")
child_4.children.create(name: "その他")
child_5 = root_12.children.create(name: "文房具/事務用品")
child_5.children.create(name: "筆記具")
child_5.children.create(name: "ノート/メモ帳")
child_5.children.create(name: "テープ/マスキングテープ")
child_5.children.create(name: "カレンダー/スケジュール")
child_5.children.create(name: "アルバム/スクラップ")
child_5.children.create(name: "ファイル/バインダー")
child_5.children.create(name: "はさみ/カッター")
child_5.children.create(name: "カードホルダー/名刺管理")
child_5.children.create(name: "のり/ホッチキス")
child_5.children.create(name: "その他")
child_6 = root_12.children.create(name: "事務/店舗用品")
child_6.children.create(name: "オフィス用品一般")
child_6.children.create(name: "オフィス家具")
child_6.children.create(name: "店舗用品")
child_6.children.create(name: "OA機器")
child_6.children.create(name: "ラッピング/包装")
child_6.children.create(name: "その他")
